# Site
name: "Ecole Arc-en-ciel"
title: "Ecole Arc-en-ciel"
description: "L'école Montessori Arc-en-ciel"
logo: 'assets/images/logo/logo.png'
favicon: 'assets/images/logo/logo.png'
baseurl: 
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'arc-en-ciel'
mailchimp-list: ~
include: 
  - "_pages"
permalink: /:title/
email: montessori.violay@gmail.com
address: 36 Rue des Genêts 42780 Violay
location_map: 'https://www.google.fr/maps/dir//36+Rue+des+Gen%C3%AAts,+42780+Violay/@45.8535438,4.3569771,17z/data=!4m17!1m7!3m6!1s0x47f468646d028e2f:0xd16927419183142f!2s36+Rue+des+Gen%C3%AAts,+42780+Violay!3b1!8m2!3d45.8535401!4d4.3591658!4m8!1m0!1m5!1m1!1s0x47f468646d028e2f:0xd16927419183142f!2m2!1d4.3591658!2d45.8535401!3e2'
phone:
  landline: '04 74 63 91 41'
  landlineLink: '+33474639141'
  mobile: '06 32 08 83 46'
  mobileLink: '+33632088346'
educational_project_url: 'https://s3.amazonaws.com/transparentclassroom.com/schools/2760/2020/attachments/37c7a7d25c9f189d89782831492e41df3a285c50.original.pdf'
educational_team_members:
  - name: "Sophie Pardigon"
    job_title: "Directrice et éducatrice 6-12 ans"
    picture: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.gQLEgtkuC4qTFctC8DJ34gHaLH%26pid%3DApi&f=1"
  - name: "Angélique Dumontet"
    job_title: "Educatrice 3-6 ans"
    picture: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.gQLEgtkuC4qTFctC8DJ34gHaLH%26pid%3DApi&f=1"
  - name: "Marie-Hélène Barbier"
    job_title: "Formatrice et ressources Montessori"
    picture: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.gQLEgtkuC4qTFctC8DJ34gHaLH%26pid%3DApi&f=1"
button_images:
  - "/assets/images/svg/button-red.svg"
  - "/assets/images/svg/button-orange.svg"
  - "/assets/images/svg/button-yellow.svg"
  - "/assets/images/svg/button-green.svg"
  - "/assets/images/svg/button-blue.svg"
  - "/assets/images/svg/button-violet.svg"
  - "/assets/images/svg/button-red.svg"
  - "/assets/images/svg/button-orange.svg"
  - "/assets/images/svg/button-yellow.svg"
  - "/assets/images/svg/button-green.svg"
  - "/assets/images/svg/button-blue.svg"
  - "/assets/images/svg/button-violet.svg"

# Events
future: true

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
