# Site
timezone: Europe/Paris
name: "Ecole Arc-en-ciel"
title: "Ecole Arc-en-ciel"
description: "L'école Montessori Arc-en-ciel"
logo: 'assets/images/logo/logo.png'
favicon: 'assets/images/logo/logo.png'
baseurl:
include:
  - "_pages"
permalink: /:title/
email: montessori.violay@gmail.com
address: 36 Rue des Genêts 42780 Violay
location_map: 'https://www.google.fr/maps/dir//36+Rue+des+Gen%C3%AAts,+42780+Violay/@45.8535438,4.3569771,17z/data=!4m17!1m7!3m6!1s0x47f468646d028e2f:0xd16927419183142f!2s36+Rue+des+Gen%C3%AAts,+42780+Violay!3b1!8m2!3d45.8535401!4d4.3591658!4m8!1m0!1m5!1m1!1s0x47f468646d028e2f:0xd16927419183142f!2m2!1d4.3591658!2d45.8535401!3e2'
phone:
  landline: '04 74 63 91 41'
  landlineLink: '+33474639141'
  mobile: '06 32 08 83 46'
  mobileLink: '+33632088346'
educational_project_url: 'https://s3.amazonaws.com/transparentclassroom.com/schools/2760/2020/attachments/37c7a7d25c9f189d89782831492e41df3a285c50.original.pdf'
educational_team_members:
  - name: "Florence Gaillard"
    job_title: "Directrice et éducatrice bilingue 6-12 ans"
    picture: "assets/images/team/florence.jpg"
    style: "background-position: 0 0;"
  - name: "Angélique Dumontet"
    job_title: "Educatrice 3-6 ans"
    picture: "assets/images/team/angelique.jpg"
    style: ""
  - name: "Bénédicte Coupat-Goutaland"
    job_title: "Educatrice 6-12 ans"
    picture: "https://user-images.githubusercontent.com/78353339/133677364-2cb1169c-3571-4c45-a686-80032ac8e946.jpeg"
    style: ""
  - name: "Cynthia Michel"
    job_title: "Assistante 3-6 ans"
    picture: "assets/images/team/cynthia.jpg"
    style: ""
button_images:
  - "/assets/images/svg/button-red.svg"
  - "/assets/images/svg/button-orange.svg"
  - "/assets/images/svg/button-yellow.svg"
  - "/assets/images/svg/button-green.svg"
  - "/assets/images/svg/button-blue.svg"
  - "/assets/images/svg/button-violet.svg"
  - "/assets/images/svg/button-red.svg"
  - "/assets/images/svg/button-orange.svg"
  - "/assets/images/svg/button-yellow.svg"
  - "/assets/images/svg/button-green.svg"
  - "/assets/images/svg/button-blue.svg"
  - "/assets/images/svg/button-violet.svg"

# Events
future: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
